/* digits.js
 * This file to contain functions/classes/etc. whatever I need
 * to deal with a digit representing interface
 */

const TOP_HORIZONTAL_BIT = 1 << 0;
const TOP_LEFT_VERTICAL_BIT = 1 << 1;
const TOP_RIGHT_VERTICAL_BIT = 1 << 2;
const MIDDLE_HORIZONTAL_BIT = 1 << 3;
const BOTTOM_LEFT_VERTICAL_BIT = 1 << 4;
const BOTTOM_RIGHT_VERTICAL_BIT = 1 << 5;
const BOTTOM_HORIZONTAL_BIT = 1 << 6;

const digitMasks = [
    // 0
    0
    | TOP_HORIZONTAL_BIT
    | TOP_LEFT_VERTICAL_BIT
    | TOP_RIGHT_VERTICAL_BIT
    // | MIDDLE_HORIZONTAL_BIT
    | BOTTOM_LEFT_VERTICAL_BIT
    | BOTTOM_RIGHT_VERTICAL_BIT
    | BOTTOM_HORIZONTAL_BIT
    | 0,

    // 1
    0
    // | TOP_HORIZONTAL_BIT
    // | TOP_LEFT_VERTICAL_BIT
    | TOP_RIGHT_VERTICAL_BIT
    // | MIDDLE_HORIZONTAL_BIT
    // | BOTTOM_LEFT_VERTICAL_BIT
    | BOTTOM_RIGHT_VERTICAL_BIT
    // | BOTTOM_HORIZONTAL_BIT
    | 0,
    

    // 2
    0
    | TOP_HORIZONTAL_BIT
    // | TOP_LEFT_VERTICAL_BIT
    | TOP_RIGHT_VERTICAL_BIT
    | MIDDLE_HORIZONTAL_BIT
    | BOTTOM_LEFT_VERTICAL_BIT
    // | BOTTOM_RIGHT_VERTICAL_BIT
    | BOTTOM_HORIZONTAL_BIT
    | 0,

    // 3
    0
    | TOP_HORIZONTAL_BIT
    // | TOP_LEFT_VERTICAL_BIT
    | TOP_RIGHT_VERTICAL_BIT
    | MIDDLE_HORIZONTAL_BIT
    // | BOTTOM_LEFT_VERTICAL_BIT
    | BOTTOM_RIGHT_VERTICAL_BIT
    | BOTTOM_HORIZONTAL_BIT
    | 0,

    // 4
    0
    // | TOP_HORIZONTAL_BIT
    | TOP_LEFT_VERTICAL_BIT
    | TOP_RIGHT_VERTICAL_BIT
    | MIDDLE_HORIZONTAL_BIT
    // | BOTTOM_LEFT_VERTICAL_BIT
    | BOTTOM_RIGHT_VERTICAL_BIT
    // | BOTTOM_HORIZONTAL_BIT
    | 0,

    // 5
    0
    | TOP_HORIZONTAL_BIT
    | TOP_LEFT_VERTICAL_BIT
    // | TOP_RIGHT_VERTICAL_BIT
    | MIDDLE_HORIZONTAL_BIT
    // | BOTTOM_LEFT_VERTICAL_BIT
    | BOTTOM_RIGHT_VERTICAL_BIT
    | BOTTOM_HORIZONTAL_BIT
    | 0,

    // 6
    0
    | TOP_HORIZONTAL_BIT
    | TOP_LEFT_VERTICAL_BIT
    // | TOP_RIGHT_VERTICAL_BIT
    | MIDDLE_HORIZONTAL_BIT
    | BOTTOM_LEFT_VERTICAL_BIT
    | BOTTOM_RIGHT_VERTICAL_BIT
    | BOTTOM_HORIZONTAL_BIT
    | 0,

    // 7
    0
    | TOP_HORIZONTAL_BIT
    // | TOP_LEFT_VERTICAL_BIT
    | TOP_RIGHT_VERTICAL_BIT
    // | MIDDLE_HORIZONTAL_BIT
    // | BOTTOM_LEFT_VERTICAL_BIT
    | BOTTOM_RIGHT_VERTICAL_BIT
    // | BOTTOM_HORIZONTAL_BIT
    | 0,

    // 8
    0
    | TOP_HORIZONTAL_BIT
    | TOP_LEFT_VERTICAL_BIT
    | TOP_RIGHT_VERTICAL_BIT
    | MIDDLE_HORIZONTAL_BIT
    | BOTTOM_LEFT_VERTICAL_BIT
    | BOTTOM_RIGHT_VERTICAL_BIT
    | BOTTOM_HORIZONTAL_BIT
    | 0,

    // 9
    0
    | TOP_HORIZONTAL_BIT
    | TOP_LEFT_VERTICAL_BIT
    | TOP_RIGHT_VERTICAL_BIT
    | MIDDLE_HORIZONTAL_BIT
    // | BOTTOM_LEFT_VERTICAL_BIT
    | BOTTOM_RIGHT_VERTICAL_BIT
    // | BOTTOM_HORIZONTAL_BIT
    | 0
]

